### ISSUE TITLE
SEO - Add image

### ISSUE THREAD

**Issue by ThomasVitale** [cloud-native-nordics/kcddenmark.dk#25]
The template configures an image to use when sharing the link on social platforms. We must update it before going live or else it will show wrong information. It's located in `static/images/social-preview.jpg`.

**Comment by rhjensen79** [comment]
That image should probably be the logo, that will be displayed on the front page, so we are consistant in how the look of the event is, across SOME.

**Comment by ryjogo** [comment]
I can perhaps sort this out when we have the final hero image done.
