### ISSUE TITLE
Parking / public transport section - Needed?

### ISSUE THREAD

**Issue by rhjensen79** [cloud-native-nordics/kcddenmark.dk#27]
I heard that there is limited parking, so imho we need to have a page, describing public transport options, and the parking situation.

**Comment by ryjogo** [comment]
Could be under #14

**Comment by rhjensen79** [comment]
Maybe we should reconsider this one again, and give it it's own section.
https://cloud-native-nordics.slack.com/archives/C04RYBHRLLR/p1690886125167469

**Comment by ThomasVitale** [comment]
I guess we can close this now
