### ISSUE TITLE
Team page - Add content

### ISSUE THREAD

**Issue by ThomasVitale** [cloud-native-nordics/kcddenmark.dk#3]
For each speaker:

* Full name
* Position (<title> at <company>)
* Picture (480x568)
* LinkedIn URL
* Twitter URL

See `src/components/pages/team/members`.

- [x] Camilla
- [x] Henrik
- [x] Jinhong
- [x] Kasper
- [x] Ophelia
- [x] Per
- [x] Robert
- [x] Ryan
- [x] Thomas
- [x] Thor

**Comment by JBrejnholt** [comment]
Jinhong Brejnholt
Chief Cloud Architect & Product Owner at Saxo Bank A/S
![72646C12-5557-45C4-AC21-3496AD569B4A_1_105_c](https://github.com/cloud-native-nordics/kcddenmark.dk/assets/19184247/f0679af4-f53d-4f9c-971a-671919ed7a48)
https://www.linkedin.com/in/jbrejnholt/
I don't use Twitter :)

**Comment by langecode** [comment]
Thor Anker Kvisgård Lange
Platform Development Specialist at Netic
![TAL](https://github.com/cloud-native-nordics/kcddenmark.dk/assets/5438266/927152a8-ef63-47d9-be41-d754dac663c4)
LinkedIn: https://www.linkedin.com/in/thor-lange-26b388/
Twitter: @thorlange

**Comment by phccdk** [comment]
Per Hedegaard Christiansen
Chief Container Platform Engineer At Saxo Bank A/S
![image](https://github.com/cloud-native-nordics/kcddenmark.dk/assets/46029452/80f35903-729a-4e31-8b2f-057a941c1fa6)

LinkedIn: http://linkedin.com/in/perhchristiansen
No twitter

**Comment by rhjensen79** [comment]
Robert Jensen
Lead Solution Engineer @ VMware
![1653650768820](https://github.com/cloud-native-nordics/kcddenmark.dk/assets/24954205/41e621e3-c9f4-41af-9f9e-568befe318fb)
[LinkedIn URL](https://www.linkedin.com/in/robertjensen/)
[Twitter URL](https://twitter.com/rhjensen)

**Comment by ryjogo** [comment]
Ryan Gough
Senior IT Operations Specialist / DevOps at JYSK
![1517607948759 (4)](https://github.com/cloud-native-nordics/kcddenmark.dk/assets/5095277/b54ea093-9e27-491b-915c-aa891f76a3e2)

https://www.linkedin.com/in/ryanjgough/
No Twitter

**Comment by tuxiem** [comment]
![organizer-camilla-larsen](https://github.com/cloud-native-nordics/kcddenmark.dk/assets/36456454/9a540d26-465f-494a-9a40-008f7a9f6049)

```js
import CamillaPhoto from './images/organizer-camilla-larsen.jpg';

    name: 'Camilla Larsen',
    position: 'Platform Engineer at Lunar',
    photo: CamillaPhoto,
    linkedinUrl: 'https://www.linkedin.com/in/camilla-larsen-tux',
    twitterUrl: '',
```

No twitter. 😄

**Comment by ThomasVitale** [comment]
"Teams" page completed: https://kcddenmark.dk/team/
