### ISSUE TITLE
Favicon - Add Image

### ISSUE THREAD

**Issue by ryjogo** [cloud-native-nordics/kcddenmark.dk#32]
Update favicon to KCD Denmark logo

https://kcddenmark.dk/

**Comment by ThomasVitale** [comment]
While we wait for the logo, I have added the Danish flag as favicon

**Comment by ThomasVitale** [comment]
Handled in https://github.com/cloud-native-nordics/kcddenmark.dk/commit/52701393e0294eeeb7a3e990d869f61435e741cb
