### ISSUE TITLE
Impressum & Data Privacy page - Add content

### ISSUE THREAD

**Issue by ThomasVitale** [cloud-native-nordics/kcddenmark.dk#7]
The "Impressum & Data Privacy" page currently includes the same text as KCD upstream theme. We must add our own details.

See `content/static-pages/data-privacy.md`.

**Comment by ryjogo** [comment]
updated and renamed to privacy policy

**Comment by ryjogo** [comment]
Generic policy generated from https://www.privacypolicygenerator.info
