### ISSUE TITLE
Header and Footer sections - Add logo

### ISSUE THREAD

**Issue by ThomasVitale** [cloud-native-nordics/kcddenmark.dk#8]
We should add the KCD Denmark logo to header and footer sections of the website, as well as update the favicon with a simplified version of the logo/icon.

See `src/icons/logo.inline.svg` and `src/images/favicon.svg`.

**Comment by ryjogo** [comment]
added logos and images on 83fd0ed91ccb3c7afae5c28d99cff0038af8aefa
